/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.amthuc.view;

import com.amthuc.dao.UserDAO;
import com.amthuc.model.User;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author ASUS_PC
 */
public class LoginPanel extends javax.swing.JPanel {
    public static User userLogin = new User(1, "", "", 2);
    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Hệ thống quản trị nhà hàng");
        add(jLabel1);
        jLabel1.setBounds(330, 140, 390, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tài khoản :");
        add(jLabel2);
        jLabel2.setBounds(330, 230, 90, 20);

        txtUName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtUName);
        txtUName.setBounds(450, 230, 210, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mật khẩu :");
        add(jLabel3);
        jLabel3.setBounds(330, 300, 90, 17);

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtPass);
        txtPass.setBounds(450, 290, 210, 30);

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogin.setText("Đăng nhập");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        add(btnLogin);
        btnLogin.setBounds(440, 350, 160, 40);

        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        add(jLabel4);
        jLabel4.setBounds(0, 0, 980, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        User user = new User();
        if (this.getTxtUName().toString().trim() != null && this.getTxtPass().toString().trim() != null) {
            try {
                user.setUsername(this.getTxtUName().toString().trim());
                user.setPassword(this.getTxtPass().toString().trim());
                
                UserDAO uDao = new UserDAO();
                User uLogin = uDao.login(user);
                if (uLogin != null) {
                    
                }else{
                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    public JPasswordField getTxtPass() {
        return txtPass;
    }

    public void setTxtPass(JPasswordField txtPass) {
        this.txtPass = txtPass;
    }

    public JTextField getTxtUName() {
        return txtUName;
    }

    public void setTxtUName(JTextField txtUName) {
        this.txtUName = txtUName;
    }

    public void addBtnLoginListener(ActionListener log) {
        btnLogin.addActionListener(log);
    }

    public JButton getBtnLogin() {
        return btnLogin;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUName;
    // End of variables declaration//GEN-END:variables
}
